config/routes.rb
Rails.application.routes.draw do
  
  resources :matches
  resources :players

  root 'players#ranking'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :player
  belongs_to :next_player, :class_name => 'Player', :foreign_key => 'next_player_id'
  belongs_to :winner_player, :class_name => 'Player', :foreign_key => 'winner_player_id'
end

app/models/player.rb
class Player < ActiveRecord::Base
    has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>"}, :default_url => "avatar_:style.png" 
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:player_id, :next_player_id, :date, :result, :winner_player_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end
  
  def player_balance(id)
    #user list matches
    player_matches = Match.where(player_id: id)
    player_matches += Match.where(next_player_id: id)

    #user is the winner
    player_winner = Match.where({player_id: id, winner_player_id: id})
    player_winner += Match.where({next_player_id: id, winner_player_id: id})

    #user lost matches
    player_lost = Match.where(player_id: id).where.not(winner_player_id: id)
    player_lost += Match.where(next_player_id: id).where.not(winner_player_id: id)

    sum = 0

    for i in player_winner do
      sum += 10
    end

    for i in player_lost do
      sum += i.result.to_i
    end

    total_matches = (player_lost.size + player_winner.size) 
    if total_matches > 0
    player_average = (sum.to_f / total_matches).round(2)
    else
    player_average = 0.to_f.round(2)
    end

    return player_average, player_matches, player_winner, player_lost
  end

  # GET /players/1
  # GET /players/1.json
  def show
    player_balance_array = player_balance(params[:id])
    # player_balance_array[0] return player_average
    # player_balance_array[1] return player_matches
    # player_balance_array[2] return player_winner
    # player_balance_array[3] return player_lost

    @player_average = player_balance_array[0]

    @player_matches = player_balance_array[1]

    @player_winner = player_balance_array[2]

    @player_lost = player_balance_array[3]

  end

  def ranking
    ranking_array_tmp = Array.new
    all_players = Player.all

    for p in all_players do

      player_balance_array = player_balance(p.id)
      ranking = player_balance_array[0] * player_balance_array[2].size
      ranking_array_tmp.push(PlayerBalanceClass.new(p.id, p.last_name, player_balance_array[0], player_balance_array[1].size, player_balance_array[2].size, ranking))

    end

    @ranking_array = ranking_array_tmp.sort_by {|x| x.ranking_player}.reverse

  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def player_params
    params.require(:player).permit(:first_name, :last_name, :avatar)
  end

  class PlayerBalanceClass
    def initialize(id, name, average, matches, winner, ranking)
      @id_player = id
      @last_name = name
      @average = average
      @number_matches = matches
      @number_winner_player = winner
      @ranking_player = ranking
    end

    def id_player
      return @id_player
    end

    def last_name
      return @last_name
    end

    def average
      return @average
    end

    def number_matches
      return @number_matches
    end

    def number_winner_player
      return @number_winner_player
    end

    def ranking_player
      return @ranking_player
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoosballTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
        <!-- First navbar -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header pull-left">
                    <a class="navbar-brand" href="/">Foosball Tracker</a>
                </div>
                <div>
			        <ul class="nav navbar-nav ">
			        	<li><%= link_to 'Matches', matches_path %></li>
                        <li><%= link_to 'Players', players_path %></li>                    
                    </ul>
         		</div>
            </div>
        </nav>
<%= yield %>

</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
	<div class="field">
		<%= f.label "Player" %>
		<br>
		<%= f.text_field :player_id, :class => 'form-control' %>
	</div>
	<div class="field">
		<%= f.label "Opponent" %>
		<br>
		<%= f.text_field :next_player_id, :class => 'form-control' %>
	</div>
	<div class="field">
		<%= f.label :date %>
		<br>
		<%= f.datetime_select :date %>
	</div>
	<div class="field">
		<%= f.label "Lost points" %>
		<br>
		<%= f.text_field :result, :class => 'form-control' %>
	</div>
	<div class="field">
		<%= f.label "Winner" %>
		<br>
		<%= f.text_field :winner_player_id, :class => 'form-control' %>
	</div>
	<div class="actions">
		<%= f.submit "Update Match", :class => "btn btn-lg btn-warning" %>
	</div>
	<% end %>
	</div>
	<div class="col-md-2"></div>
</div>

app/views/matches/edit.html.erb
<div class="container">
	<h1>Editing match</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @match, :class => "btn btn-warning btn-lg" %> 
	<%= link_to 'Back', matches_path, :class => "btn btn-warning btn-lg" %>
</div>

app/views/matches/index.html.erb
<h1>Listing matches</h1>
<div class="container">
	<table class="table">
		<thead>
			<tr>
				<th>Player</th>
				<th>Opponent</th>
				<th>Date</th>
				<th>Lost points</th>
				<th>Winner</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @matches.each do |match| %>
			<tr>
				<td><%= match.player.last_name %></td>
				<td><%= match.next_player.last_name %></td>
				<td><%= match.date %></td>
				<td><%= match.result %></td>
				<td><%= match.winner_player.last_name %></td>
				<td><%= link_to 'Show', match %></td>
				<td><%= link_to 'Edit', edit_match_path(match) %></td>
				<td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>
	<%= link_to 'New Match', new_match_path, :class => "btn btn-warning btn-lg" %>

</div>

app/views/matches/new.html.erb
<div class="container">
	<h1>New match</h1>

	<%= render 'form' %>
	<div class ="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= link_to 'Back', matches_path, :class => "btn btn-warning btn-lg" %>
		</div>
		<div class="col-md-2"></div>
	</div>
</div>

app/views/matches/show.html.erb
<div class="container">
	<p id="notice">
		<%= notice %>
	</p>
	<h1>Match</h1>

	<div class="row">
		<div class="col-md-4 text-right">
			<h2><%= @match.player.last_name %></h2>
		</div>
		<div class="col-md-4 center">
			<h3>VS</h3>
		</div>
		<div class="col-md-4">
			<h2><%= @match.next_player.last_name %></h2>
		</div>
		<br>
	</div>

	<h3>Winner: <%= @match.winner_player.last_name %></h3>
	<br>

	<h4>Lost points: <%= @match.result %></h4>
	<br>

	<h4><%= @match.date %></h4>
	<br>

	<%= link_to 'Edit', edit_match_path(@match), :class => "btn btn-warning btn-lg" %>
	<%= link_to 'Back', matches_path, :class => "btn btn-warning btn-lg" %>

</div>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
<% if @player.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

	<ul>
		<% @player.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="field">
			<div>
				<%= f.label :first_name %>:
				<br>
			</div>
			<div>
				<%= f.text_field :first_name, :class => 'form-control' %>
			</div>
		</div>
		<div class="field">
			<div>
				<%= f.label :last_name %>:
				<br>
			</div>
			<div>
				<%= f.text_field :last_name , :class => 'form-control'%>
			</div>
		</div>
		<div class="field">
			<div>
				<%= f.label :avatar %>:
				<br>
			</div>
			<div>
				<%= f.file_field :avatar, as: :file, :class => 'form-control' %>
			</div>
		</div>
		<div class="actions">
			<%= f.submit "Save", :class => "btn btn-lg btn-warning" %>
		</div>
	</div>
	<% end %>
	<div class="col-md-2"></div>
</div>

app/views/players/edit.html.erb
<div clas="container">
	<h1>Editing player</h1>

	<%= render 'form' %>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">

			<%= link_to 'Show', @player, :class => "btn btn-warning btn-lg" %>
			<%= link_to 'Back', players_path, :class => "btn btn-warning btn-lg" %>
		</div>
		<div class="col-md-2"></div>

	</div>
</div>

app/views/players/index.html.erb
<div class="container">
	<h1>Listing players</h1>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Avatar</th>
				<th>First name</th>
				<th>Last name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @players.each do |player| %>
			<tr>
				<td><%= image_tag player.avatar.url(:medium), :class => "imgList"%></td>
				<td><%= player.first_name %></td>
				<td><%= player.last_name %></td>
				<td><%= link_to 'Show', player %></td>
				<td><%= link_to 'Edit', edit_player_path(player) %></td>
				<td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>

	<%= link_to 'New Player', new_player_path, :class => "btn btn-warning btn-lg" %>

app/views/players/new.html.erb
<div class="container">
	<h1>New player</h1>

	<%= render 'form' %>
	<div class ="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<%= link_to 'Back', players_path, :class => "btn btn-warning btn-lg" %>
		</div>
		<div class="col-md-2"></div>
	</div>
</div>

app/views/players/ranking.html.erb
<h1>Player Rankings</h1>
<div class="container">

	<%= @p %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Player</th>
				<th>Average</th>
				<th>Played matches</th>
				<th>Won matches</th>
				<th>Ranking points</th>
			</tr>
		</thead>

		<tbody>
			<% number = 0 %>
			<% @ranking_array.each do |player| %>
			<% number +=1 %>
			<tr>
				<td> <%= number %></td>
				<td><%= link_to player.last_name, player_path(player.id_player) %></td>
				<td><%= player.average %></td>
				<td><%= player.number_matches  %></td>
				<td><%= player.number_winner_player  %></td>
				<td><%= player.ranking_player  %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/players/show.html.erb
<div class="container">
	<p id="notice">
		<%= notice %>
	</p>

	<div class="pull-left">
		<%= image_tag @player.avatar.url(:medium) %>
	</div>

	<div class="col-md-8">
		<h2><%= @player.first_name %> <%= @player.last_name %></h2>
	</div>

	<div class="col-md-8">
		<div class="col-md-3">
			<h4>Won:</h4>
		</div>
		<div class="col-md-3">
			<h4><%= @player_winner.size %></h4>
		</div>
	</div>

	<div class="col-md-8">
		<div class="col-md-3">
			<h4>Lost:</h4>
		</div>
		<div class="col-md-3">
			<h4><%= @player_lost.size %></h4>
		</div>

	</div>

	<div class="col-md-8">
		<div class="col-md-3">
			<h4>Average points:</h4>
		</div>
		<div class="col-md-3">
			<h4><%= @player_average %></h4>
		</div>
	</div>

	<div style="clear:both;">
		<h1>Listing matches</h1>
	</div>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Player</th>
				<th>Opponent</th>
				<th>Date</th>
				<th>Lost points</th>
				<th>Winner</th>

			</tr>
		</thead>

		<tbody>
			<% @player_matches.each do |match| %>
			<tr>
				<td><%= match.player.last_name %></td>
				<td><%= match.next_player.last_name %></td>
				<td><%= match.date %></td>
				<td><%= match.result %></td>
				<td><%= match.winner_player.last_name %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'Edit', edit_player_path(@player), :class => "btn btn-warning btn-lg"  %>
	<%= link_to 'Back', players_path, :class => "btn btn-warning btn-lg" %>

</div>